### PR TITLE
Added workflows for prettier

### LINKED ISSUE #32: GitHub workflow for Prettier
A GitHub workflow should be set up to test the formatting of PR and new pushes.

### PR DESCRIPTION
**Pull request by aditygrg2**
This closes #32 

Added workflows for prettier.

Thanks to @Shanky0 for suggesting !

### CODE REVIEW

**Comment by Shanky0** [comment]
> Added workflows for prettier.
> 
> Thanks to @Shanky0 for suggesting !

Anytime @aditygrg2 , seems like you nailed it this time. 
but got a lot of unnecessary commits. 😬

**Comment by glaslos** [comment]
Resolve conflicts.

**Comment by aditygrg2** [comment]
The branch is merged now and conflicts are resolved. Please review and let me know any feedback on improving this PR. @glaslos

**Review by glaslos — APPROVED** [review]
Nicely done! LGTM

**Pull request merged**
